services:
  nginx:
    labels:
      - traefik.http.routers.$PROJECT-nginx.entrypoints=websecure
      - traefik.http.routers.$PROJECT-nginx.tls.certresolver=letsencrypt
  traefik:
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      # Disable the default timeouts from Træfik, as they can have negative consequences,
      # like readTimeout stopping uploads after 60s by default.
      - "--entryPoints.web.transport.respondingTimeouts.readTimeout=0s"
      - "--entryPoints.web.transport.respondingTimeouts.writeTimeout=0s"
      - "--entryPoints.web.transport.respondingTimeouts.idleTimeout=0s"
      - "--entrypoints.websecure.address=:443"
      # Same timeout disabling as above, but for HTTPS.
      - "--entryPoints.websecure.transport.respondingTimeouts.readTimeout=0s"
      - "--entryPoints.websecure.transport.respondingTimeouts.writeTimeout=0s"
      - "--entryPoints.websecure.transport.respondingTimeouts.idleTimeout=0s"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=$EMAIL"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
    volumes:
      - letsencrypt:/letsencrypt
    healthcheck:
      test: nc -z -w1 traefik 443


volumes:
  letsencrypt:
