services:
  migrate:
    read_only: false
    develop:
      watch:
        - action: sync+restart
          path: ${DJANGO_ROOT}
          target: /srv
          ignore:
            - ${DJANGO_ROOT}/requirements/
  django:
    command: python manage.py runserver django:8000
    read_only: false
    develop:
      watch:
        - action: sync
          path: ${DJANGO_ROOT}
          target: /srv
          ignore:
            - ${DJANGO_ROOT}/requirements/
        - action: rebuild
          path: ${DJANGO_ROOT}/requirements
  nginx:
    labels:
      - traefik.http.routers.$PROJECT-nginx.entrypoints=web
    develop:
      watch:
        - action: rebuild
          path: ${NGINX_ROOT}
          # TODO: Watch changes in Django static files, including dependencies.
  traefik:
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.traefik.address=:8080"
    ports:
      - "8080:8080"
    labels:
      # Configures the Traefik dashboard to be displayed on DOMAIN:8080/dashboard/
      traefik.http.routers.traefik.rule: Host(`$DOMAIN`)
      traefik.http.routers.traefik.service: api@internal
      traefik.http.routers.traefik.entrypoints: traefik
  fail2ban:
    develop:
      watch:
        - action: rebuild
          path: ./fail2ban
