services:
  postgresql:
    extends:
      file: services.base.yaml
      service: postgresql
  migrate:
    extends:
      file: services.base.yaml
      service: migrate
  django:
    extends:
      file: services.base.yaml
      service: django
  nginx:
    extends:
      file: services.base.yaml
      service: nginx
    labels:
      - traefik.http.routers.$PROJECT-nginx.entrypoints=websecure
      - traefik.http.routers.$PROJECT-nginx.tls.certresolver=letsencrypt
  traefik:
    extends:
      file: services.base.yaml
      service: traefik
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=$EMAIL"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
    volumes:
      - letsencrypt:/letsencrypt
    healthcheck:
      test: nc -z -w1 traefik 443
  fail2ban:
    extends:
      file: services.base.yaml
      service: fail2ban
  ofelia:
    extends:
      file: services.base.yaml
      service: ofelia
